// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserStory_Airport;

namespace UserStory_Airport.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UserStory_Airport.models.Reisi", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("allmoney")
                        .HasColumnType("float");

                    b.Property<int>("ek_count")
                        .HasColumnType("int");

                    b.Property<double>("ek_price")
                        .HasColumnType("float");

                    b.Property<int>("nomer_reisa")
                        .HasColumnType("int");

                    b.Property<int>("passagiers_count")
                        .HasColumnType("int");

                    b.Property<double>("ppassagiers__price")
                        .HasColumnType("float");

                    b.Property<DateTime>("prib_time")
                        .HasColumnType("datetime2");

                    b.Property<double>("procent")
                        .HasColumnType("float");

                    b.Property<string>("testMigration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AirportDB");
                });
#pragma warning restore 612, 618
        }
    }
}
